### ISSUE TITLE
Add numbering to page headings 

### ISSUE THREAD

**Issue by timvink** [ignorantshr/mkdocs-add-number-plugin#1]
Hi @ignorantshr, thanks for the plugin! I was actually thinking of building the exact same thing, but found yours! 

I'd like to add numbering not only to the table of contents, but also to the headings in the page itself. Like so:

<img src='https://user-images.githubusercontent.com/5570380/75712757-bfd76380-5cc8-11ea-831e-a20adb19a21d.png' width=200 /> 

Could this be added? I'm also prepared to provide a PR if you want.

**Comment by ignorantshr** [comment]
I think this feature has been implemented, you just need to write the head in the original. You can even use the "order" option to control numbering from a few titles, and you can compare the original with the rendering effect sips through my blog: 
https://ignorantshr.github.io/question/

**Comment by timvink** [comment]
You're absolutely right, sorry for opening this issue too early !
