### ISSUE TITLE
Fix sequential headers when using multiple h1 in one page

### ISSUE THREAD

**Issue by timvink** [ignorantshr/mkdocs-add-number-plugin#12]
When within one page you have multiple headers, you need to account for that in the sequential pages. 

```html
# Header 1 page 1
# Second Heading 1 page 2
```
```html
# Header 1 page 2
```

Will render as 

```html
# 1. Header 1 page 1
# 2. Second Heading 1 page 2
```
```html
# 2. Header 1 page 2
```

But "2. Header 1 page 2" Should be "3. Header 1 page 2"

I have not implemented that logic yet..

**Comment by ignorantshr** [comment]
I have remove the `increment_pages` option.
