### ISSUE TITLE
Potential fork

### ISSUE THREAD

**Issue by timvink** [ignorantshr/mkdocs-add-number-plugin#13]
Hi @ignorantshr ,

So I found some time to continue work on this. I ended up rewriting the entire plugin to fit my own needs and making some different choices like:

- Start heading numbers at 0 until a heading 1 is encountered. This removes the need for `strict`
- Drop `include` and `exclude`
- Drop `increment_pages` (always use this)
- Drop `order` 
- Add `<span>` elements around numbers for CSS styling
- Add large unit tests and CI

I would also like to publish my plugin and call `mkdocs-enumerate-headings-plugin` (I think the name better reflects the functionality). I wanted to check first if you would be OK with that?

**Comment by ignorantshr** [comment]
Of course you can do this, it's your **freedom**, you don't have to go with my consent. As for those issues, I'll try to solve them myself later. I find myself with a lot of less than you, I will learn more from you in the future. Thank you for your contribution to this project!
