### ISSUE TITLE
add number to the link to heading

### ISSUE THREAD

**Issue by Abemii** [ignorantshr/mkdocs-add-number-plugin#14]
When we write markdown file, someone want to use link to a heading like:

```md
refer to [section a](#section-a)

## section a
foo bar
```

This plugin will update the heading and add number, but it will not update the link to the heading.
Therefore, the link will be a dead link. 
(In above example, `## section a` will be `## 1. section a`, but the link to this heading `[section a](#section-a)` will not be updated.)

Is it possible to update the link automatically?

**Comment by ignorantshr** [comment]
Yes, I have just push a [commit](https://github.com/ignorantshr/mkdocs-add-number-plugin/commit/1174c86b7ed7831185cc82fc735948345ec99d55) to fix it.
But I cann't find a API to fix the link that link to other page's heading, it's only effective on the current page.
Now you can test it again.

**Comment by ignorantshr** [comment]
Hi, @Abemii , does it work？
If you don't reply me in three days, I will close the issue.

**Comment by Abemii** [comment]
Sorry for late reply.

It worked well when I installed v1.2.2 via pypi. 
Thank you!!
