### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by timvink** [ignorantshr/mkdocs-add-number-plugin#3]
I noticed you wrote

> The following is an English description that using Google Translate

If you want I can help write a nice `README.md` in English?

**Comment by ignorantshr** [comment]
Thank you, @timvink . 
I'm glad to have a professional to help me perfect this document!

**Comment by timvink** [comment]
Would you like to keep the Chinese as well? If yes, is it OK if I put the English at the top, and the Chinese at the bottom?

**Comment by ignorantshr** [comment]
Yes, it's OK.
