### ISSUE TITLE
Sequential numbering between pages

### ISSUE THREAD

**Issue by timvink** [ignorantshr/mkdocs-add-number-plugin#4]
Hi @ignorantshr,

My team uses `MkDocs` to both publish a site and export a report as PDF (using [mkdocs-pdf-export-plugin](https://github.com/zhaoterryy/mkdocs-pdf-export-plugin)).

I would like to have the numbering increment for each main page. That way, you can refer to specific sections in the PDF report.

Happy to work on a PR if you're interested in adding this feature?

**Comment by ignorantshr** [comment]
Hi @timvink ,
 Could you show me the effect, I don't know exactly what you mean.
> I would like to have the numbering increment for each main page. 

As for PDF, I don't need it right now, but who knows later, so you can add this feature to your heart, and it's best to provide an option to control whether or not to output PDF.

**Comment by timvink** [comment]
Let's say I have this website:

![image](https://user-images.githubusercontent.com/5570380/76144391-173a5280-6080-11ea-9793-9418f33256f7.png)

Then I would expect `page two` to start with `2.`, but it starts counting again:

![image](https://user-images.githubusercontent.com/5570380/76144397-2f11d680-6080-11ea-88ab-50a437509d2f.png)

We could build in an option that increments the main number for each page. One idea would be to use the `on_files()` [event](https://www.mkdocs.org/user-guide/plugins/#on_files)

**Comment by ignorantshr** [comment]
Oh, I see. 
You can do it.
Thanks again.

**Comment by timvink** [comment]
Was a bit more work than I thought, but I have it working! Now making sure it also respects the includes & excludes, and adding some unit tests. Will submit PR probably later this week.

**Comment by ignorantshr** [comment]
It doesn't matter, you can do it in your free time.
