### ISSUE TITLE
Add entrypoint for `add-number`

### ISSUE THREAD

**Issue by timvink** [ignorantshr/mkdocs-add-number-plugin#6]
MkDocs plugin have the naming convention `mkdocs-<name>-plugin` but for entrypoint, leave out the "mkdocs-" and "-plugin".

We can add another entrypoint to `setup.py`, e.g. from: 

```python
    entry_points={
        'mkdocs.plugins': [
            'mkdocs-add-number-plugin=mkdocs_add_number_plugin.plugin:AddIndexPlugin'
        ]
    }
```

to:

```python
    entry_points={
        'mkdocs.plugins': [
            'mkdocs-add-number-plugin=mkdocs_add_number_plugin.plugin:AddIndexPlugin',
            'add-number=mkdocs_add_number_plugin.plugin:AddIndexPlugin'
        ]
    }
```

And then update the `README.md` appriopriately.

**Comment by timvink** [comment]
Oh and while we're at it, we can change the plugin class `AddIndexPlugin` to `AddNumberPlugin`, it will help users identify the plugin on any errors

**Comment by timvink** [comment]
Happy to submit PR for this..

**Comment by ignorantshr** [comment]
OK, just do as you say.
There is no environment for development because of the outbreak in China. So you can go and realize your idea.And thank you for your contribution to this plugin.

**Comment by timvink** [comment]
Oh, are you based in Wuhan? Must be crazy out there. I'm from the Netherlands, not too many cases here yet but a lot of attention from the news

**Comment by ignorantshr** [comment]
No, I'm in other provinces, not a disaster area.Although the outbreak has been brought under control, I have not been allowed to return to work.The virus is very contagious, must wear a mask when you go out.

**Comment by timvink** [comment]
I haven't seen anyone wearing a mask here, yet. Impressive that the outbreak has been controlled.. huge effort from China!
