### ISSUE TITLE
Update description of plugin

### ISSUE THREAD

**Issue by timvink** [ignorantshr/mkdocs-add-number-plugin#9]
![image](https://user-images.githubusercontent.com/5570380/76251313-1b649c80-6247-11ea-9974-84f14b977b68.png)

Shall we update to

> [MkDocs](https://www.mkdocs.org/) plugin to automatically number the headings (h1-h6) in each markdown page.

?

**Comment by ignorantshr** [comment]
Yes.

**Comment by timvink** [comment]
I cannot do this, as I am not the owner of this repository. You could add me as a collaborator, or do it yourself :)

**Comment by ignorantshr** [comment]
Hi, @timvink .
I think it's better to invite you to be an collaborator because you've contributed a lot to the project, thank you very much.

**Comment by timvink** [comment]
Thanks!

But even now there is no edit button for me:

![image](https://user-images.githubusercontent.com/5570380/76391453-d9834580-636f-11ea-8490-6eeae3d8e8ef.png)

Can you do it?

**Comment by ignorantshr** [comment]
OK, I have rewritten the description. But it doesn't seem to support `mkdown` syntax.Is that OK？

**Comment by timvink** [comment]
Indeed it doesn't. Better to remove the link then.
